"后台运行
FORM FRM_BATCH.
PERFORM FRM_UPLOAD_DATA.

DATA: T_SEL1,
T_SEL2,
T_SEL3.

T_SEL1 = P_SEL1.
T_SEL2 = P_SEL2.
T_SEL3 = P_SEL3.

CALL FUNCTION 'ZPM00130' STARTING NEW TASK 'ZPM00130'
EXPORTING
P_SEL1 = T_SEL1
P_SEL2 = T_SEL2
P_SEL3 = T_SEL3
TABLES
GT_DATA = GT_DATA.

IF SY-SUBRC = 0.
    MESSAGE '已开始后台任务，本窗口将关闭。' TYPE 'I'.
    LEAVE TO SCREEN 0.
ENDIF.
ENDFORM.