SELECTION-SCREEN: FUNCTION KEY 1.
SELECTION-SCREEN BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
PARAMETERS:
P_PATH TYPE CHAR200 MODIF ID M1,
P_UP RADIOBUTTON GROUP G1 DEFAULT 'X' USER-COMMAND USR1,
P_DOWN RADIOBUTTON GROUP G1.
SELECTION-SCREEN END OF BLOCK B1.

SELECTION-SCREEN BEGIN OF BLOCK B2 WITH FRAME TITLE TEXT-002.
SELECTION-SCREEN BEGIN OF LINE.
SELECTION-SCREEN POSITION 1.
PARAMETERS P_SEL1 RADIOBUTTON GROUP G2 DEFAULT 'X' USER-COMMAND USR2.
SELECTION-SCREEN COMMENT 2(5) TEXT-005 FOR FIELD P_SEL1.
SELECTION-SCREEN POSITION 12.
PARAMETERS P_SEL2 RADIOBUTTON GROUP G2.
SELECTION-SCREEN COMMENT 13(7) TEXT-006 FOR FIELD P_SEL2.
SELECTION-SCREEN END OF LINE.

SELECTION-SCREEN ULINE /1(50).
PARAMETERS P_SEL3(2) AS LISTBOX VISIBLE LENGTH 8 DEFAULT '1'.
SELECTION-SCREEN END OF BLOCK B2.

SELECTION-SCREEN BEGIN OF BLOCK B3 WITH FRAME TITLE TEXT-007.
PARAMETERS P_SEL4 RADIOBUTTON GROUP G3 DEFAULT 'X' USER-COMMAND USR3.
PARAMETERS P-SEL5 RADIOBUTTON GROUP G3.
SELECTION-SCREEN END OF BLOCK B3.