FORM DATA_PROCESS.
    DATA: L_PERC TYPE I VALUE 0,
    L_LINE TYPE STRING,
    L_TOTAL TYPE STRING,
    L_STXT TYPE STRING,
    L_SPERC(3) TYPE C,
    ZTSTM TYPE STRING.
    
    

    IF P_SEL1 = 'X'.
        
        ELSEIF P_SEL2 = 'X'.
    ENDIF.
ENDFORM.

FORM UPDATA USING GS_DATA TYPE TY_DISPLAY.
GS_DATAC = GS_DATA.
CLEAR GS_DATAC-SIGN.
PERFORM CHECK USING GS_DATA.
IF SY-SUBRC = 0.
    
ENDIF.
ENDFORM.

FORM UPDATA2 USING GS_DATA2 TYPE TY_DISPLAY2.
XXXXXXXXX
ENDFORM.