FORM CHECK USING GS_DATA TYPE TY_DISPLAY.
    IF P_SEL3 = '1'.
        XXXXXXXXX
    ENDIF.
ENDFORM.

FORM CHECK2 USING GS_DATA2 TYPE TY_DISPLAY2.
    IF P_SEL3 = '1'.
        XXXXXXXXX
    ENDIF.
ENDFORM.