DATA: BDCDATA LIKE BDCDATA OCCURS 0 WITH HEADER LINE.
DATA: DATA_GENERAL LIKE BAPI_ITOB,
DATA_GENERALX LIKE BAPI_ITOBX,
DATA_SPECIFIC LIKE BAPI_ITOB_EQ_ONLY,
DATA_SPECIFICX LIKE BAPI_ITOB_EQ_ONLYX,
RETURN LIKE BAPIRET2,
GS_EQUI TYPE EQUI.

DATA: GT_DATA2 TYPE TABLE OF ZPMT00130LOG,
GS_DATA2 TYPE ZPMT00130LOG.

DATA ERROR_TXT TYPE STRING.

DATA UUID TYPE SYSUUID_X16.

DATA FUNCTXT TYPE SMP_DYNTXT.

DATA STMP_TOTAL TYPE STRING.

DATA: INIT,
CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
EDITOR TYPE REF TO CL_GUI_TEXTEDIT.

FIELD-SYMBOLS <DYN_FIELD> TYPE ANY.

DATA: M1(256) TYPE C OCCURS 0,
LINE(256) TYPE C.

DATA: OK_CODE TYPE SY-UCOMM,
SAVE_OK TYPE SY-UCOMM.

DATA: GV_FULLPATH TYPE STRING,
GV_PATH TYPE STRING,
GV_NAME TYPE STRING.

DATA: GT_FIELDCAT TYPE LVC_T_FCAT,
GS_FIELDCAT TYPE LVC_S_FCAT,
GS_LAYOUT TYPE LVC_S_LAYO.

DATA: GT_NAME TYPE VRM_ID,
GT_LIST TYPE VRM_VALUES,
GS_LIST LIKE LINE OF GT_LIST.

TYPES: BEGIN OF TY_DISPLAY,
CHECK,
SIGN TYPE CHAR5,
MSG TYPE CHAR300,
NUM TYPE STRING.
INCLUDE STRUCTURE ZPMS00130D.
TYPES: END OF TY_DISPLAY.

TYPES: BEGIN OF TY_DISPLAY2,
CHECK,
SIGN TYPE CHAR5,
MSG TYPE CHAR300,
NUM TYPE STRING.
INCLUDE STRUCTURE ZPMS00130D2.
TYPES: END OF TY_DISPLAY2.

DATA: GS_DATAC TYPE TY_DISPLAY,
GS_DATAC2 TYPE TY_DISPLAY2,
GT_DATA TYPE TABLE OF ZPMS00130T,
GT_ALV_DATA TYPE TABLE OF TY_DISPLAY,
GS_ALV_DATA TYPE TY_DISPLAY,
GT_DELETED TYPE TABLE OF TY_DISPLAY,
GT_ALV_DATA2 TYPE TABLE OF TY_DISPLAY2,
GS_ALV_DATA2 TYPE TY_DISPLAY2,
GT_DELETED2 TYPE TABLE OF TY_DISPLAY2.

FIELD-SYMBOLS:
<FS> TYPE ZPMS00130T,
<FS_DATA> TYPE TY_DISPLAY,
<FS_DATA2> TYPE TY_DISPLAY2,
<FS_DATA3> TYPE ZPMT00130LOG.
