FORM BDC_DYNPRO USING PROGRAM DYNPRO.
    CLEAR BDCDATA.
    BDCDATA-PROGRAM = PROGRAM.
    DBCDATA-DYNPRO = DYNPRO.
    DBCDATA-DYNBEGIN = 'X'.
    APPEND BDCDATA.
ENDFORM.

FORM BDC_FIELD USING FNAM FVAL.
CLEAR BDCDATA.
BDCDATA-FNAM = FNAM.
BDCDATA-FVAL = FVAL.
APPEND BDCDATA.
ENDFORM.

FORM SEND_SIP USING I_EQUNR TYPE EQUNR.
REFRESH BDCDATA.
PERFORM BDC_DYNPRO USING 'SAPMIEQ0' '0100'.
PERFORM BDC_FIELD USING 'BDC_CURSOR'
'RM63E-EQUNR'.
PERFORM BDC_FIELD USING 'BDC_OKCODE'
'/00'.
PERFORM BDC_FIELD USING 'RM63E-EQUNR'
I_EQUNR.
PERFORM BDC_DYNPRO USING 'SAPMIEQ0' '0101'.
PERFORM BDC_FIELD USING 'BDC_OKCODE'
'=BU'.
CALL TRANSACTION 'IE02' USING BDCDATA MODE 'N'.

CALL FUNCTION 'BAPI_TRANSACTION_COMMIT'.
IF SY-SUBRC = 0.
    MESSAGE '推送成功' TYPE 'S'.
ELSE.
    MESSAGE '推送失败' TYPE 'E'.
ENDIF.
ENDFORM.