REPORT ZMMR_XZGXCBB.
INCLUDE ZMMR_XZGXCBB_TOP.
INCLUDE ZMMR_XZGXCBB_SCREEN.
INCLUDE ZMMR_XZGXCBB_FORM.
INCLUDE ZMMR_XZGXCBB_DISPLAY.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_DATE-LOW.
PERFORM S_SET_SELECTION_LOW.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR S_DATE-HIGH.
PERFORM S_SET_SELECTION_HIGH.

AT SELECTION-SCREEN ON VALUE-REQUEST FOR P_OUTIN.
PERFORM P_SET_SELECTION2.

START-OF-SELECTION.
PERFORM FRM_INIT_DATA.
PERFORM FRM_GET_DATA.
PERFORM FRM_PROCESS_DATA.