TABLES: ZMMT00040,
        MSEG,
        ZMMT00091,
        LFA1,
        MAKT,
        MARA.

TYPE-POOLS: SLIS.

DATA: LT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
        WT_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
        LS_LAYOUT TYPE SLIS_LAYOUT_ALV.

DATA: I_DATA TYPE SY-DATUM.

TYPES: BEGIN OF TDATA,
    MATNR TYPE MSEG-MATNR,
    CHARG TYPE MSEG-CHARG,