TYPE-POOLS:CNTL.
TABLES:/BIN/PZTASK_ID.
DATA: REF_GRID_ALV TYPE REF TO CL_GUI_ALV_GRID,
REF_GRID_TREE TYPE REF TO CL_GUI_ALV_TREE,
REF_CONTAINER_TREE TYPE REF TO CL_GUI_CONTAINER,
REF_CONTAINER_ALV TYPE REF TO CL_GUI_CONTAINER,
REF_CONTAINER_PARENT TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
REF_SPLITTER TYPE REF TO CL_GUI_SPLITTER_CONTAINER.
DATA: LS_VARI TYPE DISVARIANT.
DATA: GT_FCAT_TREE TYPE LVC_T_FCAT.
DATA: G_CUR_NODE_H TYPE TABLE OF LVC_NKEY.
DATA MR_TOOLBAR TYPE REF TO CL_GUI_TOOLBAR.

DATA: BEGIN OF GT_OUT OCCURS 0,
POSID(24) TYPE C,
POSID_1(24) TYPE C,
LX(5) TYPE C,
MC(50) TYPE C,
NODEID TYPE LVC_NKEY,
CK TYPE C,
END OF GT_OUT.

DATA: T_OUT LIKE TABLE OF GT_OUT WITH HEADER LINE.
FIELD-SYMBOLS: <FS> LIKE GT_OUT.
FIELD-SYMBOLS: <FS2> LIKE GT_OUT.

DATA: T_RCC8 TYPE SORTED TABLE OF /B28/HDBDRCC8 WITH UNIQUE KEY NODEID WITH HEADER LINE.
DATA: T_RCC8_1 TYPE SORTED TABLE OF /B28/HDBDRCC8 WITH UNIQUE KEY NODEID WITH HEADER LINE.
DATA: WA_RCC8 TYPE /B28/HDBDRCC8.
DATA: W_NODEID TYPE /B28/HDBDRCC8-NODEID.
DATA: T_YSJD LIKE HASHED TABLE OF ZZYSSJD WITH UNIQUE KEY POSID WITH HEADER LINE.
FIELD-SYMBOLS <FS_YSJD> TYPE ZZYSSJD.
DATA: LT_SELECTED_NODES TYPE LVC_T_NKEY,
L_SELECTED_NODE TYPE LVC_NKEY,
L_RC TYPE C.
DATA LT_SEL_COL TYPE LVC_T_FNAM.
DATA: L_FNAME TYPE LVC_FNAME.
DATA: WA_OUT LIKE GT_OUT,
WA_OUT1 LIKE GT_OUT,
WA_OUT2 LIKE GT_OUT.
DATA: LT_ITEM_LAYOUT TYPE LVC_T_LAYI.
DATA: ES_NODE_LAYOUT TYPE LVC_S_LAYN.
DATA L_NODE_KEY TYPE LVC_VALUE.
DATA W_INDEX TYPE SY-TABIX.
DATA NODE_KEY TYPE LVC_NKEY.     