REPORT colorOfWrite.
*BACK GROUD
FORMAT COLOR COL_HEADING.
WRITE 'HELLO WORLD'.
SKIP.
WRITE 'WELCOME'.
SKIP.
SKIP.

*FRONT GROUND
FORMAT COLOR COL_HEADING INVERSE ON.
WRITE 'HELLO WORLD'.
SKIP.
WRITE 'WELCOME'.