READ TABLE GT_OUT INDEX RS_SELFIELD-TABINDEX.
CONCATENATE GS_OUT-ZJYDBM '-' GS_OUT-ZJYDXH '-' LV_ZJYDZXH INTO L_INPUT.
SELECT SINGLE ZURL INTO L_ADRESS FROM XXX WHERE XXX = XXXX.
IF SY-SUBRC = 0.
    L_ADRESS = L_ADRESS && L_INPUT.
    CALL FUNCTION 'CALL_INTERNET_ADRESS'
    EXPORTING
    PI_ADRESS = L_ADRESS
    EXCEPTIONS
    NO_INPUT_DATA = 1
    OTHERS = 2.
ELSE.
    MESSAGE S024 WITH '请先维护附件上传地址'.
ENDIF.