TYPE1.

DATA: BEGIN OF STMP OCCURS 0,
I_TIP1(100),
END OF STMP.

DATA: I_TIP1 TYPE STRING.

SELECT I_TIP1 FROM ZT802LOG INTO I_TIP1 WHERE UUID = XXXXXXX
ENDSELECT.

CALL FUNCTION 'SCMS_STRING_TO_FTEXT' "STING 转内表
EXPORTING
TEXT = I_TIP1
TABLES
FTEXT_TAB = STMP.

CALL FUNCTION 'ADA_POPUP_WITH_TABLE'
EXPORTING
STARTPOS_COL = 1
STARTPOS_ROW = 1
TITLETEXT = XXXXXXX
WORDWRAP_POSITION = XXXXXXX
TABLES
VALUETAB = STMP.



TYPE2.

DATA: I_TIP1 TYPE STRING.
DATA: BEGIN OF STMP OCCURS 0,
I_TIP1(100),
END OF STMP.

SELECT I_TIP1 FROM ZT802LOG INTO I_TIP1 WHERE UUID = XXXXXXX
ENDSELECT.

SPLIT I_TIP1 AT ',' INTO TABLE STMP. "以','对STRING进行拆分，拆分后存入内表

DATA: STMP_TOTAL TYPE STRING. "将分割取消的','重新加入内表
DESCRIBE TABLE STMP LINES STMP_TOTAL.
LOOP AT STMP ASSIGNING FIELD-SYMBOL(<FS>).
IF SY-TABIX = STMP_TOTAL. "最后一行不执行
    EXIT.
ENDIF.
CONCATENATE <FS>-I_TIP1 ',' INTO <FS>->I_TIP1.
ENDLOOP.

CALL FUNCTION 'ADA_POPUP_WITH_TABLE'
EXPORTING
STARTPOS_COL = 1
STARTPOS_ROW = 1
TITLETEXT = XXXXXXX
WORDWRAP_POSITION = XXXXXXX
TABLES
VALUETAB = STMP.


TYPE3.

DATA: LV_SJSON TYPE STRING,
LV_FIELD TYPE CHAR30. 
DATA: GT_ITAB TYPE TABLE OF ZT802LOG.
SELECT I_TIP1 UUID FROM ZT802LOG INTO CORRESPONDING FIELDS OF TABLE GT_ITAB WHERE UUID = XXXXXXX.

READ TABLE GT_ITAB ASSIGNING FIELD-SYMBOL(<FS_ALV>) WITH KEY UUID = XXXXXXX.
IF SY-SUBRC = 0.
    LV_SJSON = <FS_ALV>-I_TIP1.
    CL_DEMO_OUTPUT=>NEW(
    )->BEGIN_SECTION('')
    ->WRITE_JSON(LV_SJSON)->END_SECTION(
    )->DISPLAY().
ENDIF.