****** POP SCREEN ******
*** 31082023 ***

REPORT popScreen.

DATA: L_RET TYPE C,
GIT_TAB TYPE STANDARD TABLE OF SVAL WITH HEADER LINE.

CLEAR GIT_TAB.
GIT_TAB-TABNAME = 'AFKO'.
GIT_TAB-FIELDNAME = 'AUFNR'.
GIT_TAB-FIELDTEXT = '生产订单号'.
GIT_TAB-FIELD_attr = '02'.
GIT_TAB-VALUE = '0100000001'.
APPEND GIT_TAB.
CLEAR GIT_TAB.

GIT_TAB-TABNAME = 'AFKO'.
GIT_TAB-FIELDNAME = 'GAMNG'.
GIT_TAB-FIELDTEXT = '订单数量'.
GIT_TAB-FIELD_attr = ''.
APPEND GIT_TAB.
CLEAR GIT_TAB.

CALL FUNCTION 'POPUP_GET_VALUES_USER_HELP'
EXPORTING
POPUP_TITLE = 'TITLE_TEXT'
IMPORTING
FIELDS = GIT_TAB
EXCEPTIONS
ERROR_IN_FIELDS = 1
OTHERS = 2.

IF SY-SUBRC <> 0.
    ****
ELSE.
    READ TABLE GIT_TAB INDEX 2.
    IF SY-SUBRC = 0.
        CONSDENSE GIT_TAB-VALUE. "去除空格
        WRITE: GIT_TAB-VALUE LEFT-JUSTIFIED.
    ENDIF.
ENDIF.