REPORT simpleREUSE_ALV.
TABLES MKPF.
TABLES MSEG.

DATA WA_MKPF LIKE TABLE OF MKPF WITH HEADER LINE.
SELECT-OPTIONS S_MJAHR FOR MKPF-MJAHR.
START-OF-SELECTION.
SELECT MJAHR MBLNR FROM MKPF.
INTO CORRESPONDING FIELDS OF TABLE WA_MKPF WHERE MJAHR IN S_MJAHR.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
EXPORTING
I_STRUCTURE_NAME = 'MKPF'
TABLES
T_OUTTAB = WA_MKPF
EXCEPTIONS
PROGRAM_ERROR = 1
OTHERS = 2.