"JSON 转换
FUNCTION ZPS_FUN_MAIN_JSON.
*******************************************************
*本地接口
*IMPORTING
*VALUE(E_TAB)
*EXPORTING
*VALUE(ZJSON) TYPE STRING
*******************************************************
DATA: ZTREXJSON TYPE REF TO CL_TREX_JSON_SERIALIZER.
CREATE OBJECT ZTREXJSON
EXPORTING
DATA = E_TAB.

CALL METHOD ZTREXJSON->SERIALIZE.

CALL METHOD ZTREXJSON->GET_DATA
RECEVING
RVAL = ZJSON.

ENDFUNCTION.