TABLES ZFIT00060.
TABLES: ANLA,ANLB,ANLC,ANLP.

TYPE-POOLS: SLIS.

DATA: LT_FIELDCAT TYPE SLIS_T_FIELDCAT_ALV WITH HEADER LINE,
    WT_FIELDCAT TYPE SLIS_FIELDCAT_ALV,
    LS_LAYOUT TYPE SILIS_LAYOUT_ALV.

TYPES: BEGIN OF TDATA,
    BUKRS TYPE ANLB-BUKRS,
    ANLN1 TYPE ANLB-ANLN1,
    TXT50 TYPE ANLA-TXT50,
    ANLKL TYPE ANLA-ANLKL,
    AFABE TYPE AFABE_D,
    AFASL TYPE ANLB-AFASL,
    NDJAR TYPE ANLB-NDJAR,
    NDURJ TYPE ANLB-NDURJ,
    ANLC TYPE DMBTR,
    GJAHR TYPE ANLP-GJAHR,
    PERAF TYPE ANLP-PERAF,
    KOSTL TYPE ANLP-KOSTL,
    HKONT TYPE HKONT,
    KTEXT TYPE CSKT-KTEXT,
    KTNAFG TYPE T095B-KTNAFG,
    TXT50II TYPE SKAT-TXT50,
    KTOGR TYPE T095B-KTOGR,
    SAKNR TYPE SKAT-SAKNR,
    NAFAZ TYPE ANLP-NAFAZ,
    SAFAG TYPE ANLP-SAFAG,
    AAFAG TYPE ANLP-AAFAG,
    DYZJJE TYPE DMBTR,
    YSSJDYZJJE TYPE DMBTR,
    CHAZHI TYPE DMBTR,
    KANSW TYPE ANLC-KANSW,
    ANSWL TYPE ANLC-ANSWL,
    SETNAME TYPE SETLEAF-SETNAME,
    SAKAN TYPE ZFIT00060-SAKAN,
    END OF TDATA.

DATA: ITAB TYPE TABLE OF TDATA WITH HEADER LINE,
    ITAB1 TYPE TABLE OF TDATA WITH HEADER LINE.

DATA ANLC_TEMP TYPE DMBTR.

RANGES R_ANLKL FOR ANLA-ANLKL.
REFRESH R_ANLKL.
RANGES R_PERAF FOR ANLP-PERAF.
REFRESH R_PERAF. 