SELECTION-SCREEN BEGIN OF BLOCK BLK1 WITH FRAME TITLE TEXT-T01.
SELECT-OPTIONS S_BUKRS FOR ANLB-BUKRS.
PARAMETERS P_GJAHR TYPE ANLP-GJAHR OBLIGATORY DEFAULT SY-DATUM.
PARAMETERS S_SEASON AS LISTBOX VISIBLE LENGTH 8 OBLIGATORY DEFAULT '1'.
SELECT-OPTIONS S_KOSTL FOR ANLP-KOSTL.
SELECT-OPTIONS S_ANLKL FOR ANLA-ANLKL.
SELECT-OPTIONS S_ANLN1 FOR ANLB-ANLN1.
SELECTION-SCREEN END OF BLOCK BLK1.

FORM P_SET_SELECTION.
    TYPES: BEGIN OF TY,
    COL1 TYPE CHAR1,
    COL2 TYPE CHAR4,
    END OF TY.

    DATA STAB TYPE TABLE OF TY.
    STAB = VALUE #( 
        ( COL1 = '1' COL2 = '第一季度' )
        ( COL1 = '2' COL2 = '第二季度' )
        ( COL1 = '3' COL2 = '第三季度' )
        ( COL1 = '4' COL2 = '第四季度' )
     ).

     CALL FUNCTION 'F4IF_INT_TABLE_VALUE_REQUEST'
     EXPORTING
     RETFIELD = 'COL1'
     DYNPPROG = SY-REPID
     DYNPNR = SY-DYNNR
     DYNPROFIELD = 'COL1'
     VALUE_ORG = 'S'
     CALLBACK_PROGRAM = SY-REPID
     TABLES
     VALUE_TAB = STAB
     EXCEPTIONS
     PARAMETER_ERROR = 1
     NO_VALUES_FOUND = 2
     OTHERS = 3.
     IF SY-SUBRC <> 0.
        MESSAGE ID SY-MSGID TYPE SY-MSGTY NUMBER SY-MSGNO
        WITH SY-MSGV1 SY-MSGV2 SY-MSGV3 SY-MSGV4.
     ENDIF.